
//! Autogenerated weights for `blog_pallet`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2025-11-05, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Victus`, CPU: `12th Gen Intel(R) Core(TM) i5-12450H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// target/release/dacs-node
// benchmark
// pallet
// --wasm-execution
// compiled
// --chain
// dev
// --pallet
// blog_pallet
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/blog-pallet/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for `blog_pallet`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Blog::NextPostId` (r:1 w:1)
	/// Proof: `Blog::NextPostId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Blog::PostLikes` (r:1 w:0)
	/// Proof: `Blog::PostLikes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blog::AuthorPosts` (r:1 w:1)
	/// Proof: `Blog::AuthorPosts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blog::Posts` (r:0 w:1)
	/// Proof: `Blog::Posts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_post() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3593`
		// Minimum execution time: 39_402_000 picoseconds.
		Weight::from_parts(43_632_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Blog::Posts` (r:1 w:1)
	/// Proof: `Blog::Posts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_post() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `3696`
		// Minimum execution time: 9_874_000 picoseconds.
		Weight::from_parts(10_405_000, 0)
			.saturating_add(Weight::from_parts(0, 3696))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Blog::Posts` (r:1 w:1)
	/// Proof: `Blog::Posts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn delete_post() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `3696`
		// Minimum execution time: 9_651_000 picoseconds.
		Weight::from_parts(10_360_000, 0)
			.saturating_add(Weight::from_parts(0, 3696))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Blog::Posts` (r:1 w:0)
	/// Proof: `Blog::Posts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blog::PostComments` (r:1 w:1)
	/// Proof: `Blog::PostComments` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Blog::NextCommentId` (r:1 w:1)
	/// Proof: `Blog::NextCommentId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Blog::Comments` (r:0 w:1)
	/// Proof: `Blog::Comments` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_comment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `538`
		//  Estimated: `6196`
		// Minimum execution time: 45_657_000 picoseconds.
		Weight::from_parts(46_796_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Blog::Comments` (r:1 w:1)
	/// Proof: `Blog::Comments` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_comment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `226`
		//  Estimated: `3691`
		// Minimum execution time: 9_481_000 picoseconds.
		Weight::from_parts(9_908_000, 0)
			.saturating_add(Weight::from_parts(0, 3691))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Blog::Comments` (r:1 w:1)
	/// Proof: `Blog::Comments` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn delete_comment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `226`
		//  Estimated: `3691`
		// Minimum execution time: 9_174_000 picoseconds.
		Weight::from_parts(10_048_000, 0)
			.saturating_add(Weight::from_parts(0, 3691))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Blog::Posts` (r:1 w:1)
	/// Proof: `Blog::Posts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blog::PostLikedBy` (r:1 w:1)
	/// Proof: `Blog::PostLikedBy` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blog::PostLikes` (r:1 w:1)
	/// Proof: `Blog::PostLikes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn toggle_post_like() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `261`
		//  Estimated: `3726`
		// Minimum execution time: 16_357_000 picoseconds.
		Weight::from_parts(17_361_000, 0)
			.saturating_add(Weight::from_parts(0, 3726))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Blog::Comments` (r:1 w:0)
	/// Proof: `Blog::Comments` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blog::CommentLikedBy` (r:1 w:1)
	/// Proof: `Blog::CommentLikedBy` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blog::CommentLikes` (r:1 w:1)
	/// Proof: `Blog::CommentLikes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn toggle_comment_like() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `284`
		//  Estimated: `3749`
		// Minimum execution time: 14_376_000 picoseconds.
		Weight::from_parts(15_877_000, 0)
			.saturating_add(Weight::from_parts(0, 3749))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Blog::Posts` (r:1 w:0)
	/// Proof: `Blog::Posts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blog::PostTags` (r:1 w:1)
	/// Proof: `Blog::PostTags` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_tags() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `3696`
		// Minimum execution time: 13_352_000 picoseconds.
		Weight::from_parts(13_999_000, 0)
			.saturating_add(Weight::from_parts(0, 3696))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Blog::Posts` (r:1 w:0)
	/// Proof: `Blog::Posts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blog::UserBookmarks` (r:1 w:1)
	/// Proof: `Blog::UserBookmarks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blog::PostBookmarkedBy` (r:1 w:1)
	/// Proof: `Blog::PostBookmarkedBy` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn toggle_bookmark() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `3696`
		// Minimum execution time: 13_346_000 picoseconds.
		Weight::from_parts(14_117_000, 0)
			.saturating_add(Weight::from_parts(0, 3696))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Blog::IsFollowing` (r:1 w:1)
	/// Proof: `Blog::IsFollowing` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blog::AuthorFollowers` (r:1 w:1)
	/// Proof: `Blog::AuthorFollowers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blog::UserFollowing` (r:1 w:1)
	/// Proof: `Blog::UserFollowing` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn toggle_follow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3471`
		// Minimum execution time: 12_360_000 picoseconds.
		Weight::from_parts(13_380_000, 0)
			.saturating_add(Weight::from_parts(0, 3471))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}

/// Weight functions for tests and backwards compatibility.
impl crate::WeightInfo for () {
 fn create_post() -> Weight {
  Weight::zero()
 }
 fn update_post() -> Weight {
  Weight::zero()
 }
 fn delete_post() -> Weight {
  Weight::zero()
 }
 fn create_comment() -> Weight {
  Weight::zero()
 }
 fn update_comment() -> Weight {
  Weight::zero()
 }
 fn delete_comment() -> Weight {
  Weight::zero()
 }
 fn toggle_post_like() -> Weight {
  Weight::zero()
 }
 fn toggle_comment_like() -> Weight {
  Weight::zero()
 }
 fn add_tags() -> Weight {
  Weight::zero()
 }
 fn toggle_bookmark() -> Weight {
  Weight::zero()
 }
 fn toggle_follow() -> Weight {
  Weight::zero()
 }
}
